# Batch.toml

# [[entries]]
# PCR productについての情報を記載します。複数回定義することができます。
# name       :PCR productの名前を指定します(例: "ATnGXXXXX")。
# amplicon   :プライマーで挟まれた(プライマー配列を含まない)、増幅配列 (センス鎖 5' -> 3')を記入します。
# fw_primer	 :Forwardプライマー配列 (センス鎖 5' -> 3')を指定します。
# rv_primer	 :Reverseプライマー配列 (アンチセンス鎖 5' -> 3')を指定します。


[[entries]]
name = "example_1"
amplicon = "ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG"
fw_primer = "AATCGATCG"
rv_primer = "A"

[[entries]]
name = "example_2"
amplicon = "TCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCG"
fw_primer = "TCGATCGTCGATCG"
rv_primer = "ATCGATCGTCGATCG"

[[entries]]
name = "example_3"
amplicon = "ATCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCGTCGATCG"
fw_primer = "TTTTCGATCGYTTAAG"
rv_primer = "TACATCTCGATCGCT"

[[entries]]
...
...
...
...

[[entries]]
...
...
...
...

[[entries]]
...
...
...
...

[[entries]]
...
...
...
...
